### PR TITLE
Rspec upgrade

### PR DESCRIPTION
**Pull request by piotrb**
**Feature:**
Saw some deprecations and upgraded the syntax using the transpec gem. Nothing really changing here.

**Ticket:**
-

**Submitter Checklist:**
- [x] CI Passing
- [ ] PR Linked to Asana Ticket
- [x] Hound Appeased Acceptably
- [x] No Code Climate Issues
- [x] Class, Module, and public method comments up to spec

**Reviewer Checklist:**
- [ ] New Code Tested Effectively
- [ ] Code organization meets SOP standards
- [ ] Does this code fullfill the ticket?

**Only Then:**
- [ ] Move ticket in Asana

### CODE REVIEW

**Comment by piotrb** [comment]
This also now contains a huge amount of Hound fixes

**Comment by vincentpaca** [comment]
Hmm your long polling PR seems to be included here.

**Comment by piotrb** [comment]
Oh weird let me rebase ..

**Comment by piotrb** [comment]
rspec is still passing

**Pull request merged**
